### ISSUE TITLE
API to send different tasks each group host

### ISSUE THREAD

**Issue by tomviner** [lordmauve/chopsticks#10]
I've been working on https://github.com/SupercomputerInABriefcase/SuperComputerInABriefcase today - with the aim of running tasks on a cluster of Raspberry PIs as an educational exercise in distributed computing.

After a good while trying to understand/install OpenMPI (on laptop and PIs), I decided to try chopsticks and [had it working in about 5 minutes](https://github.com/SupercomputerInABriefcase/SuperComputerInABriefcase/blob/master/chop.py).

But this sends the same task to each host in the group. Obviously we want to send different tasks to each host and send another task when that finishes.

Could this be done by either: a) passing in a list, or even better an iterator, of functions, to `group.call` and have the work spread across the hosts. Or b) add a `call_async` method to tunnel that takes a callback?

**Comment by lordmauve** [comment]
Yes, I think both are reasonable. The APIs for async calls are there behind the scenes - look at chopsticks/group.py to see how they can be used.

**Comment by lordmauve** [comment]
I made a start on this in 2ce6f6b22085b79712235cb0f9f6e5c78b457f6d. Not sure about the API yet - it's always hard to describe synchronous APIs for async operations - and it has no support for groups. I might end up documenting it as experimental and cutting a 0.6 version.

**Comment by lordmauve** [comment]
This is done. See http://chopsticks.readthedocs.io/en/latest/queues.html

(Release still pending).
