### ISSUE TITLE
EP2017 Sprint details

### ISSUE THREAD

**Issue by dimaqq** [lordmauve/chopsticks#36]
@lordmauve 
Hi Daniel, are there any details on chopsticks spring at EuroPython 2017?
Like exact day and time perhaps?
Thanks.

**Comment by lordmauve** [comment]
Hi @dimaqq. Yes, we'll be sprinting Saturday and Sunday. I'm hoping to get there for 09:30 tomorrow. I'm leaving mid-afternoon on Sunday but there might be people around who would like to continue...

**Comment by dimaqq** [comment]
Sorry I didn't make it then.
