### ISSUE TITLE
Traceback on slow connections when using python3

### ISSUE THREAD

**Issue by amigrave** [lordmauve/chopsticks#52]
Hi @lordmauve ,

I've encountered a bug which took me quite a while to pinpoint: when using chopsticks with python3 on slow network connection, the reading of the bootstrap code through stdin fails.

Actually I originally encountered the bug when patching `bubble.py` whose file size became bigger and the connection to a google cloud engine server was slow, hence triggering the bug described here below. No need to say that I though for days that some of my code in `bubble.py` was the culprit before finding out it was just due to the filesize :)

Consider the following file:

```python
# test.py
import sys
from chopsticks.tunnel import SSHTunnel

def test():
    return 'done'

tunnel = SSHTunnel(sys.argv[1])
print(tunnel.call(test))
```

I'm using a vm on my local computer for testing and when I want to throttle the connection I use this line in my ssh config:

```
Host foobar
    ProxyCommand pv -q -L 50k | nc %h 22
```

now consider the following test script executions:

```
$ python2 test.py server
done

$ python2 test.py server.slow  # with throttling
done

$ python3 test.py server
done

$ python3 test.py server.slow  # with throttling
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print(tunnel.call(test))
  File "/home/amigrave/.local/lib/python3.5/site-packages/chopsticks/tunnel.py", line 296, in call
    self.connect()
  File "/home/amigrave/.local/lib/python3.5/site-packages/chopsticks/tunnel.py", line 142, in connect
    raise RemoteException(res.msg)
chopsticks.tunnel.RemoteException: Unexpected EOF on stream
```

The reason for this behavior lays in the bootstrap inline code executed with the python interpreter command line:

```python
# tunnel.py#SubprocessTunnel
    PYTHON_ARGS = [
        '-usS',
        '-c',
        'import sys, os; sys.stdin = os.fdopen(0, \'rb\', 0); ' +
        '__bubble = sys.stdin.read(%d); ' % len(bubble) +
        'exec(compile(__bubble, \'bubble.py\', \'exec\'))'
    ]
```

The way we read stdin: `'import sys, os; sys.stdin = os.fdopen(0, \'rb\', 0); ' +`.
So in python3 `os.fdopen` is an alias to `open` and for a reason I don't yet fully understand (maybe unbuffered file descriptors are set to `os.O_NONBLOCK` ?) the `os.stdin.read(size)` call will not return the good amount of bytes.
That said, in the [python documentation](https://docs.python.org/3.3/tutorial/inputoutput.html#methods-of-file-objects) it is stated

> To read a file’s contents, call f.read(size), which reads some quantity of data and returns it as a string or bytes object. size is an optional numeric argument. When size is omitted or negative, the entire contents of the file will be read and returned; it’s your problem if the file is twice as large as your machine’s memory. **Otherwise, at most size bytes are read and returned**. If the end of the file has been reached, f.read() will return an empty string ('').

So it seems to be a normal behavior !?
Here's a line you can add in the boostrap code in order to check the fact (on my box it actually reads 16kb instead of 17030 bytes):

```diff
        'import sys, os; sys.stdin = os.fdopen(0, \'rb\', 0); ' +
        '__bubble = sys.stdin.read(%d); ' % len(bubble) +
+        'sys.stderr.write(\'Read %d - Got %%d\' %% len(__bubble)); ' % len(bubble) +
        'exec(compile(__bubble, \'bubble.py\', \'exec\'))'
```

And here's the result on my box with ssh throttling:

```
$ python3 test.py 192.168.56.103
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print(tunnel.call(test))
  File "/home/amigrave/.local/lib/python3.5/site-packages/chopsticks/tunnel.py", line 296, in call
    self.connect()
  File "/home/amigrave/.local/lib/python3.5/site-packages/chopsticks/tunnel.py", line 142, in connect
    raise RemoteException(res.msg)
chopsticks.tunnel.RemoteException: Unexpected EOF on stream
[root@server.slow] Read 17030 - Got 16384
```

I always worked with such behavior for `socket.recv` but I didn't knew it could happen to file objects (although I hope this only happens in special cases otherwise I won't sleep this week thinking about all the code I wrote so far). 

So. I tried to fix it with a `while` loop in order to ensure we get all bytes before compiling the bootstrap code but you cannot syntactically use a `while` statement in an oneliner containing other statements.
I tried other approaches:
- `eval`ing a multiline string with `\n` replaced to `\\n`
- base64 encoding then decoding/execing the code
- writing the bootstrap code to a file then execing

but all approaches failed somewhere mainly because I lack the time to do it properly and also because I felt bad during my attempts which always looked like a pile of hacks on top of hacks.

This is why I think this issue needs to be fixed by you. I tried to compile as much information as possible in this issue so you can think about what would be the best option.

**Comment by lordmauve** [comment]
This is a very detailed report, and an interesting issue. I will look into it.

**Comment by lordmauve** [comment]
It looks as though the change in Python 3 is that an unbuffered file object opened with fdopen no longer returns exactly `size` bytes - instead it focuses on only doing one system call.

We don't actually need an unbuffered file object in general - when we create 'inpipe' in bubble.py, it is buffered. However, the problem is that if we make the `sys.stdin` file object in `PYTHON_ARGS` buffered, it could read extra data into its buffers, which is thrown away in `bubble.py` once we dup all the file descriptors around and open inpipe.

Here's a slightly odd solution that I think might work - only buffer the exact amount we need:

```python
PYTHON_ARGS = [                                                                 
    '-usS',                                                                     
    '-c',                                                                       
    'import sys, os; _bsz = %d ;' % len(bubble) +                               
    'sys.stdin = os.fdopen(0, \'rb\', _bsz); ' +                                
                                                                                
    '__bubble = sys.stdin.read(_bsz); ' +                                       
    'exec(compile(__bubble, \'bubble.py\', \'exec\'))'                          
]  
```

Could you try this and let me know if it works for you?

**Comment by lordmauve** [comment]
I'm not very happy with that actually. What we really need to do is keep hold of whatever is in the buffer - either modify or re-use the file object. I guess the simplest thing would be to do the stdin `dup()` in `PYTHON_ARGS` and don't re-open stdin in `bubble.py`.

**Comment by amigrave** [comment]
Here's my attempt following your directives. Tested on python2.7 and python3.5
