### ISSUE TITLE
Custom SSH port with Chopsticks

### ISSUE THREAD

**Issue by oba11** [lordmauve/chopsticks#8]
I was wondering if its possible to use custom SSH port with chopstick tunnel.
Thanks

**Comment by lordmauve** [comment]
Not currently, but there are a couple of workarounds.

chopsticks just uses the normal `ssh` binary, so you can put any additional options into `~/.ssh/config`, eg.

    Host *.mydomain.com
        Port 20022

Alternatively, you can subclass `chopsticks.tunnel.SSHTunnel` and override [cmd_args](https://github.com/lordmauve/chopsticks/blob/master/chopsticks/tunnel.py#L442) to pass a `-p` option when `ssh` is called.

As you say, this should be built-in though.

**Comment by oba11** [comment]
Using my SSH config works perfectly which is more than enough for me now.
Thanks
